//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     If you have other needs, you can write another partial class.
// </auto-generated>
//------------------------------------------------------------------------------

using ProtoBuf;

namespace DataTable
{
	[ProtoContract]
	public partial class Item
	{
		public Item() {
		}

		/// <summary>
		/// id
		/// </summary>
		[ProtoMember(1)]
		public int id { private set; get; }

		/// <summary>
		/// string测试
		/// </summary>
		[ProtoMember(2)]
		public string ut_string { private set; get; }
	}
}
