//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     If you have other needs, you can write another partial class.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataTable
{
	public partial class DataDataReader : BaseReader<Data>
	{
		public DataDataReader()
		{
			Load("Data");
		}
	}
}
